### ISSUE TITLE
Review Kubewarden stats on clomonitor.io

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden.io#120]
Kubewarden has been added to the clomonitor website: https://clomonitor.io/projects/cncf/kubewarden

This is a website that collects stats about the different projects that are part of CNCF. We should look into these results and come up wih action items about how to boost the yellow/red area.

### Action items

* [x] Add kwctl to the list of repositories (Raul)
* [x] Add SDKs to the list of repositories (Raul)
* [x] change policy-server repository type to not be `code-lite` (Raul)
* Fix the following red items:
  * [x] adopters
  * [ ] governance (not needed)
  * [x] #122
  * [x] website
  * [x] #123
  * [x] #124
  * [x] #127
  * [x] #125
  * [x] #126
  * [x] trademark disclaimer

~For later iteraitons:~
~* [ ] #128~
~* [ ] #129~
Update: we are going to keep track of these two items with their dedicated cards.

In case help is needed, we can reach out to @tegioz, who works on this website.

**Comment by raulcabello** [comment]
PR for adding missing repositiories -> https://github.com/cncf/clomonitor/pull/554

**Comment by raulcabello** [comment]
@flavio can you add kubewarden website to all repositories, please? I don't have permissions. That's the reason [website](https://clomonitor.io/docs/topics/checks/#website) is red

**Comment by flavio** [comment]
> @flavio can you add kubewarden website to all repositories, please? I don't have permissions. That's the reason [website](https://clomonitor.io/docs/topics/checks/#website) is red

Done!

**Comment by flavio** [comment]
Closing, everything has been done
