### ISSUE TITLE
CNCF Sandbox project checklist

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden.io#130]
The CNCF Technical Oversight Committee needs some action from us Kubewarden, so we are listed in https://www.cncf.io/sandbox-projects/. See https://github.com/cncf/toc/issues/858.

This issue is a copy of their published TODO as an epic, so we can mark things as done, and create cards as necessary.

---

From the project side, please ensure that you:

- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Understand the trademark guidelines: https://www.linuxfoundation.org/legal/trademark-usage
- [x] Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
- [x] Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/
  * not yet
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details)
Is your project in its own separate neutral github organization?
- [x] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io/
- [x] Create maintainer list + add to aggregated https://maintainers.cncf.io/ list by submitting a PR to it
- [x] Have added your project to https://github.com/cncf/contribute
- [x] #141
- [x] #142

Things that CNCF will need from the project:

- [x] Provide emails for the maintainers added to https://maintainers.cncf.io/ in order to get access to the maintainers mailing list and ServiceDesk
- [x] #143
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] https://github.com/kubewarden/automation/issues/27
- [x] GitHub: ensure that hat the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
- [x] #144
- [x] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

(edit Dec 14th 2023, new requirement, license scan).
- [x] License scan, like Fossa or Snyk (we were already compliant, see https://github.com/kubewarden/kubewarden.io/issues/130#issuecomment-1855641022)

**Comment by flavio** [comment]
PR for submission against CNCF's landscape is open: https://github.com/cncf/landscape/pull/2746

**Comment by flavio** [comment]
PR with list of maintainers: https://github.com/cncf/foundation/pull/428

**Comment by flavio** [comment]
PR for the contributors website: https://github.com/cncf/tag-contributor-strategy/pull/243

**Comment by flavio** [comment]
artwork repo: we're missing some images. I've reached out to the SUSE UX team

**Comment by viccuad** [comment]
For "CII: Start on a CII best practices badge", shall we count it as done, as listed in https://bestpractices.coreinfrastructure.org/en/projects?q=kubewarden ?

**Comment by flavio** [comment]
> For "CII: Start on a CII best practices badge", shall we count it as done, as listed in https://bestpractices.coreinfrastructure.org/en/projects?q=kubewarden ?

I think we are meeting some of the requirements that are still left unchecked. I would leave that open, so that we can go through the list

**Comment by viccuad** [comment]
Added a new requirement to the list, license scan with tools like Fossa or Synk (see this [comment](https://github.com/cncf/toc/issues/858#issuecomment-1854532380)).

Marked as completed, as we have FOSSA enabled in all the user facing repositories (not on our own libraries), each repository has the badge, and is passing. See:

https://github.com/kubewarden/kwctl
https://github.com/kubewarden/kubewarden-controller
https://github.com/kubewarden/policy-server
https://github.com/kubewarden/audit-scanner

**Comment by jvanz** [comment]
This is done. Closing issue :partying_face: :rocket:
