### ISSUE TITLE
Blog post about KW 1.15.0

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden.io#243]
Write a blog post covering the changes introduced by 1.15:

- [ ] Extend PolicyServer CRD to have tolerations: https://github.com/kubewarden/kubewarden-controller/issues/752
- [ ] Helm chart: have a central place where tolerations, affinity and anti-affinity rules are specified and then enforced to all the components of our stack: https://github.com/kubewarden/kubewarden-controller/issues/756
- [ ] Kubewarden controller: more technical debt removed
- [ ] Implement policy grouping code: do policy-server changes
- [ ] CEL policy:
  - [ ] add OCI capability that fetches configs https://github.com/kubewarden/cel-policy/issues/53
  - [ ] lazy variable evaluation
- [ ] Extend our ClusterAdmissionPolicy, AdmissionPolicy CRDs to include matchConditions: https://github.com/kubewarden/kubewarden-controller/issues/758 [TENTATIVE]
